export const APP_NAME = 'APP_FOREST';
export const CURRENT_STORE = 'CURRENT_STORE';
export const APP_STORE = 'APP_STORE'
export const SUBCRIPTION_STORE = 'SUBCRIPTION_STORE'
export const UPCOMING_SUBCRIPTION_STORE = 'UPCOMING_SUBCRIPTION_STORE'
